# Generated by Django 4.0.5 on 2022-06-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fishka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('reverse', models.CharField(max_length=1024)),
                ('meaning', models.CharField(max_length=128)),
            ],
        ),
    ]
