# Generated by Django 3.2 on 2022-06-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0002_fishka'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
        migrations.RemoveField(
            model_name='fishka',
            name='meaning',
        ),
    ]
