# Generated by Django 4.0.5 on 2022-11-01 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishka',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishka',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
