# Generated by Django 4.0.5 on 2022-06-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0003_auto_20220617_1530'),
        ('fiszki', '0003_delete_react_remove_fishka_meaning'),
    ]

    operations = [
    ]
