# Generated by Django 4.0.5 on 2022-11-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0003_fishka_author_fishka_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('op1', models.CharField(max_length=64)),
                ('op2', models.CharField(max_length=64)),
                ('op3', models.CharField(max_length=64)),
                ('op4', models.CharField(max_length=64)),
                ('answer', models.CharField(max_length=64)),
            ],
        ),
    ]
