# Generated by Django 4.0.5 on 2022-11-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0005_alter_fishka_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishka',
            name='author',
        ),
        migrations.RemoveField(
            model_name='fishka',
            name='category',
        ),
    ]
