# Generated by Django 4.0.5 on 2022-11-06 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0006_remove_fishka_author_remove_fishka_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishka',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fishka',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
