# Generated by Django 4.0.5 on 2022-11-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0007_fishka_author_fishka_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='quiz_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fiszki.quiz'),
            preserve_default=False,
        ),
    ]
