# Generated by Django 4.0.5 on 2022-11-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0008_quiz_customuser_quiz_points_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionFK', to='fiszki.quiz'),
        ),
    ]
