# Generated by Django 4.0.5 on 2022-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0011_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='solved_quests',
            field=models.ManyToManyField(null=True, to='fiszki.question'),
        ),
    ]
